# Overrides to support Compose, ignore test suites for some rules.
# The below represents an *opinion* based on recommendations from Detekt.
# Start here and apply your preferred override strategy!:
# https://detekt.dev/docs/introduction/compose
complexity:
  LongMethod:
    ignoreAnnotated:
      - 'Composable'
  LongParameterList:
    ignoreDefaultParameters: true
    ignoreAnnotated:
      - 'Composable'
  TooManyFunctions:
    ignoreAnnotated:
      - 'Preview'
naming:
  FunctionNaming:
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
    ignoreAnnotated:
      - 'Composable'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
style:
  MagicNumber:
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
    ignoreAnnotated:
      - 'Composable'
  UnusedPrivateMember:
    ignoreAnnotated:
      - 'Preview'
      - 'Composable'