name: Detekt without Type Resolution

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  without-type-resolution:
    permissions:
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Run detekt
        run: ./gradlew detekt

      - name: Upload Detekt Reports
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Reports
          path: app/build/reports/detekt

      # Make sure we always run this reporting task,
      # because the previous step may fail if there are findings.
      - name: Upload SARIF to GitHub using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: app/build/reports/detekt/detekt.sarif
